# Spree Editor TinyMCE Configuration
#
# These are the options that will automatically be passed into the tinyMCE.init function
# whenever TinyMCE is loaded in one of your spree pages. Please edit this file to
# customise your TinyMCE setup in your spree installation. If you wish to see the full
# range of configuration options then please go here:
#
#    http://www.tinymce.com/wiki.php/configuration

# TinyMCE Options
selector: "textarea"
theme: "advanced"
language: "ru"
skin: "o2k7"
# schema: "html5-strict"
# element_format: "html"
plugins: 
   -layer
   -table
   -insertdatetime
   -preview
   -media
   -searchreplace
   -contextmenu
   -paste
   -directionality
   -fullscreen
   -noneditable
   -visualchars
   -nonbreaking
   -template

# Theme options
theme_advanced_styles : "Header 1=header1;Header 2=header2;Header 3=header3;Table Row=tableRow1"
theme_advanced_buttons1: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview"
theme_advanced_buttons2: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,sub,sup,|,bullist,numlist,|,outdent,indent,blockquote,|,"
theme_advanced_buttons3: "styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor"
theme_advanced_buttons4: "tablecontrols,|,hr,removeformat,visualaid"
theme_advanced_buttons5: "fullscreen,|,charmap,media,|,visualchars,blockquote"
theme_advanced_toolbar_location: "top"
# theme_advanced_toolbar_align: "left"
theme_advanced_statusbar_location: "top"
theme_advanced_resizing: false